
TARGET_FILE_FIELD='targetFile'
TARGET_METHOD_FIELD='targetMethod'
TARGET_METHOD_ARGS_FIELD='targetMethodArgs'
TARGET_METHOD_RETURN_FIELD='targetMethodReturn'
CHALLENGE_YAML='challenge.yaml'
API_ADRESS='127.0.0.1'
API_PORT=6070
MISSION_USER_SCORE_ENDPOINT='/deadlock/cli/mission/score'
MISSION_USER_SCORE_FILENAME='mission-user'